mutation LoginUser($email: String!, $password: String!) {
  sigIn(data: { email: $email, password: $password }) {
    token
    expiresIn
    user {
      id
      name
      username
      email
      bio
      phone
    }
  }
}
