mutation LoginUser($email: String!, $password: String!) {
  sigIn(data: { email: $email, password: $password }) {
    token
    expiresIn
    user {
      id
      name
      username
      email
      bio
      phone
      photo
    }
  }
}

mutation CreateUser(
  $name: String!
  $username: String!
  $email: String!
  $password: String!
) {
  signup(
    data: {
      name: $name
      email: $email
      bio: "none"
      phone: "none"
      password: $password
      username: $username
    }
  ) {
    id
    name
    username
    email
    bio
    phone
  }
}

mutation UpdateUser($user: UpdateUserDTO!) {
  updateUser(data: $user) {
    id
  }
}

query GetOneUser($username: String!) {
  FindOneUser(userName: $username) {
    id
    username
    name
    photo
    bio
  }
}
