mutation LoginUser($email: String!, $password: String!) {
  sigIn(data: { email: $email, password: $password }) {
    token
    expiresIn
    user {
      id
      name
      username
      email
      bio
      phone
      photo
      cover
    }
  }
}

mutation CreateUser(
  $name: String!
  $username: String!
  $email: String!
  $password: String!
) {
  signup(
    data: {
      name: $name
      email: $email
      password: $password
      username: $username
    }
  ) {
    id
    name
    username
    email
    bio
    phone
  }
}

mutation UpdateUser($user: UpdateUserDTO!) {
  updateUser(data: $user) {
    id
  }
}

query GetOneUser($username: String!) {
  FindOneUser(userName: $username) {
    id
    username
    name
    photo
    bio
    cover
  }
}

query searchUser($user: String!) {
  searchUsers(searchInput: $user) {
    id
    name
    username
    photo
    bio
  }
}

query getFollowers($id: String!) {
  getFollowers(id: $id) {
    userID
    createdAt
    userTofollowID
  }
}

query getFollowing($id: String!) {
  GetFollowing(id: $id) {
    userID
    createdAt
    userTofollowID
  }
}

mutation followUser($id: String!) {
  followUser(data: { userIdToFollow: $id }) {
    id
    userID
  }
}
